on:
  push:
    branches: [main, test-build-ci]
  pull_request:
    branches: [main]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for cached dist folder
        id: cache-wasm
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ hashFiles('**/wasm.c', '**/build-wasm.sh') }}
      - name: Build wasm binaries
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        uses: addnab/docker-run-action@v3
        with:
          image: emscripten/emsdk
          options: -v ${{ github.workspace }}:/src -e CI
          run: |
            mkdir dist && ./build-wasm.sh

  test-browsers-latest:
    runs-on: ubuntu-latest
    needs: build-wasm
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Retrieve cached dist folder
        uses: actions/cache/restore@v3
        id: cache-wasm
        with:
          path: dist
          key: dist-${{ hashFiles('**/wasm.c', '**/build-wasm.sh') }}
        # ignore cache miss, since it was taken care of the `build-wasm` step and it should never occur here

      - name: Install Chrome
        run: npx playwright install-deps chrome

      - name: Install Firefox
        run: npx playwright install-deps firefox

      - name: Install Webkit
        run: npx playwright install-deps webkit

      - name: Run browser tests
        run: npm run test-browser

  test-browsers-compatibility:
    runs-on: ubuntu-latest
    needs: build-wasm
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Retrieve cached dist folder
        uses: actions/cache/restore@v3
        id: cache-wasm
        with:
          path: dist
          key: dist-${{ hashFiles('**/wasm.c', '**/build-wasm.sh') }}
        # ignore cache miss, since it was taken care of the `build-wasm` step and it should never occur here

      - name: Run browserstack tests
        run: npm run test-browser -- --browsers bs_ios_14,bs_safari_13_1

  test-node:
    runs-on: ubuntu-latest
    needs: build-wasm
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Retrieve cached dist folder
        uses: actions/cache/restore@v3
        id: cache-wasm
        with:
          path: dist
          key: dist-${{ hashFiles('**/wasm.c', '**/build-wasm.sh') }}
        # ignore cache miss, since it was taken care of the `build-wasm` step and it should never occur here

      - name: Run node tests
        run: npm test